### ISSUE TITLE
Error when use that config

### ISSUE THREAD

**Issue by crashbit666** [FStanDev/myNvimConfig#1]
Failed to run `config` for nightfox.nvim

/home/crashbit/.config/nvim/lua/configs/lazy.lua:47: Vim:E185: Cannot find color scheme 'Duskfox'

# stacktrace:
  - .config/nvim/lua/configs/lazy.lua:47 _in_ **config**
  - .config/nvim/lua/base/plugins/lazy.lua:15
  - .config/nvim/lua/base/init.lua:21
  - .config/nvim/init.lua:1
  
  After that I run 
  runtimepath=~/.config/nvim,~/.local/share/nvim/lazy/lazy.nvim,~/.local/share/nvim/lazy/nvim-treesitter,~/.local/share/nvim/lazy/plenary.nvim,~/.local/share/nvim/lazy/telescope.nvim,~/.local/share/nvim/lazy/nvim-dap,~/.local/share/nvim/lazy/nvim-web-devicons,~/.lo
cal/share/nvim/lazy/nvim-tree.lua,~/.local/share/nvim/lazy/mason-lspconfig.nvim,~/.local/share/nvim/lazy/mason.nvim,~/.local/share/nvim/lazy/nvim-lspconfig,~/.local/share/nvim/lazy/rustaceanvim,~/.local/share/nvim/lazy/nightfox.nvim,/usr/share/nvim/runtime,/usr/sha
re/nvim/runtime/pack/dist/opt/matchit,/usr/lib/nvim,~/.local/state/nvim/lazy/readme

**Comment by FStanDev** [comment]
My bad, is duskfox with lowercase, I'll change it right now

**Comment by FStanDev** [comment]
@crashbit666 last commit solve this issue

**Comment by crashbit666** [comment]
Ok, thanks
